### ISSUE TITLE
Create class DeviceController

### ISSUE THREAD

**Issue by johnythefarmer** [MindDev-development/MinDroid#15]
There should be made a Class which connects GameController and devices

**Comment by vrenclouff** [comment]
I create and add Keyboard class to DeviceController class. 
I would create the class DeviceController as Singleton because it will be only once in this program.
 I replaced the parameter MindWaves in the GameController constructor by DeviceController.

**Comment by johnythefarmer** [comment]
Created signals and slots to connect GameController to devices. There is still some work to be done, like trying to reconnect to device, but that is not the subject of this issue so i think it can be closed.
