### ISSUE TITLE
Signal disconnect, what happens

### ISSUE THREAD

**Issue by vrenclouff** [MindDev-development/MinDroid#27]
What happens when the signal from mindwave is disconnected. 
The game stops and MindWaves tries to connect again.

**Comment by vrenclouff** [comment]
tgo

**Comment by vrenclouff** [comment]
DeviceController is connect to GuiController.
When MindWave is disconnect GuiController show pop up windows and user can touch try reconnect button. After player can continue with game.

**Comment by johnythefarmer** [comment]
Game is now working and devices are normally reconnected.
