### ISSUE TITLE
Track class not compilable

### ISSUE THREAD

**Issue by johnythefarmer** [MindDev-development/MinDroid#31]
When I try to compile the app, I get following error:

.../MinDroid\Physics\track.cpp:45: error: undefined reference to `createBonus(Type, int, int)'

When I look in the **Track**  header file, there really is not any method named createBonus.
Please write it ASAP and add comments, because I really can't tell what any of those methods in Track class does.

**Comment by DJ-Foton** [comment]
In file <b>bonus.h</b> is <i>Bonus *createBonus(Type type, int lane, int position);</i> and I forgot to change it to this: <i>Bonus *createBonus(Type type, Lane lane, int position);</i>.
