### ISSUE TITLE
Program stop working when device start connecting

### ISSUE THREAD

**Issue by DJ-Foton** [MindDev-development/MinDroid#37]
I chose the device in <b>Settings</b> and clicked on <b>Play</b>. If the label <i>Connecting to devices, please wait</i> had shown up, program stop working.

Qt listing: <i>
"74:E5:43:89:61:4D"  starting thread
"74:E5:43:89:60:25"  starting thread
The program has unexpectedly finished.
</i>

**Comment by johnythefarmer** [comment]
Fixed!!
The reason was that app was started on Windows. There is now implementation of QBluetooth working on Windows. The bluetooth code was erased. It now works fine.
